// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Interop {

struct TypeName;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup {

struct IXamlType;
struct XmlnsDefinition;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup {

struct IXamlMetadataProvider;

}

WINRT_EXPORT namespace winrt::BlankApp1 {

struct IMainPage;
struct MainPage;
struct XamlMetaDataProvider;

}

namespace winrt::impl {

template <> struct category<BlankApp1::IMainPage>{ using type = interface_category; };
template <> struct category<BlankApp1::MainPage>{ using type = class_category; };
template <> struct category<BlankApp1::XamlMetaDataProvider>{ using type = class_category; };
template <> struct name<BlankApp1::IMainPage>{ static constexpr auto & value{ L"BlankApp1.IMainPage" }; };
template <> struct name<BlankApp1::MainPage>{ static constexpr auto & value{ L"BlankApp1.MainPage" }; };
template <> struct name<BlankApp1::XamlMetaDataProvider>{ static constexpr auto & value{ L"BlankApp1.XamlMetaDataProvider" }; };
template <> struct guid_storage<BlankApp1::IMainPage>{ static constexpr guid value{ 0x75C42149,0x0D5F,0x5911,{ 0x9E,0xB9,0x54,0x26,0xAA,0x1D,0x1E,0x08 } }; };
template <> struct default_interface<BlankApp1::MainPage>{ using type = BlankApp1::IMainPage; };
template <> struct default_interface<BlankApp1::XamlMetaDataProvider>{ using type = Windows::UI::Xaml::Markup::IXamlMetadataProvider; };

template <> struct abi<BlankApp1::IMainPage>{ struct type : IInspectable
{
};};

template <typename D>
struct consume_BlankApp1_IMainPage
{
};
template <> struct consume<BlankApp1::IMainPage> { template <typename D> using type = consume_BlankApp1_IMainPage<D>; };

}
