// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Interop.0.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.0.h"
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/RuntimeComponent3.RuntimeComponent3_XamlTypeInfo.0.h"

WINRT_EXPORT namespace winrt::RuntimeComponent3::RuntimeComponent3_XamlTypeInfo {

}
