// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Interop.1.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.1.h"
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/RuntimeComponent3.RuntimeComponent3_XamlTypeInfo.1.h"

WINRT_EXPORT namespace winrt::RuntimeComponent3::RuntimeComponent3_XamlTypeInfo {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::RuntimeComponent3::RuntimeComponent3_XamlTypeInfo {

struct WINRT_EBO XamlMetaDataProvider :
    Windows::UI::Xaml::Markup::IXamlMetadataProvider,
    impl::require<XamlMetaDataProvider, Windows::Foundation::IStringable>
{
    XamlMetaDataProvider(std::nullptr_t) noexcept {}
    XamlMetaDataProvider();
};

}
