// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Interop {

struct TypeName;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup {

struct IXamlType;
struct XmlnsDefinition;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup {

struct IXamlMetadataProvider;

}

WINRT_EXPORT namespace winrt::RuntimeComponent3::RuntimeComponent3_XamlTypeInfo {

struct XamlMetaDataProvider;

}

namespace winrt::impl {

template <> struct category<RuntimeComponent3::RuntimeComponent3_XamlTypeInfo::XamlMetaDataProvider>{ using type = class_category; };
template <> struct name<RuntimeComponent3::RuntimeComponent3_XamlTypeInfo::XamlMetaDataProvider>{ static constexpr auto & value{ L"RuntimeComponent3.RuntimeComponent3_XamlTypeInfo.XamlMetaDataProvider" }; };
template <> struct default_interface<RuntimeComponent3::RuntimeComponent3_XamlTypeInfo::XamlMetaDataProvider>{ using type = Windows::UI::Xaml::Markup::IXamlMetadataProvider; };

}
