// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Markup.0.h"
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Windows.UI.Composition.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.0.h"
#include "winrt/impl/RuntimeComponent3.0.h"

WINRT_EXPORT namespace winrt::RuntimeComponent3 {

struct WINRT_EBO IMyUserControl1Class :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMyUserControl1Class>
{
    IMyUserControl1Class(std::nullptr_t = nullptr) noexcept {}
};

}
